// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
)

type BusinessInCategory struct {
	ID         int64
	CategoryID int64
	Name       string
	Url        string
	Page       int64
}

type BusinessInfo struct {
	ID            int64
	TradeName     sql.NullString
	BusinessName  sql.NullString
	Address       sql.NullString
	PhoneNumber   sql.NullString
	Email         sql.NullString
	Website       sql.NullString
	SocialMedia   sql.NullString
	CanonicalLink string
	Rating        sql.NullFloat64
	Description   sql.NullString
}

type Category struct {
	ID          int64
	Name        string
	Url         string
	Size        int64
	IsCompleted int64
}
